-- Day 10: New Year’s Resolution Progress Tracker
-- This query calculates the progress and success category for each friend’s New Year’s resolutions.
SELECT FRIEND_NAME, 
COUNT(RESOLUTION) AS N_RESOLUTIONS, 
SUM(IS_COMPLETED) AS N_COMPLETED, 
(SUM(IS_COMPLETED)/COUNT(RESOLUTION))*100 AS SUCCESS_PERCENTAGE,
CASE WHEN (SUM(IS_COMPLETED)/COUNT(RESOLUTION))*100 > 75 THEN 'green'
WHEN  (SUM(IS_COMPLETED)/COUNT(RESOLUTION))*100 BETWEEN 50 AND 75 THEN 'yellow'
ELSE 'red' END AS SUCCESS_CATEGORY  
FROM RESOLUTIONS 
GROUP BY FRIEND_NAME