-- Day 6: Top 3 Polar Bears by Distance Traveled
-- This query retrieves the top 3 polar bears by total distance traveled in December 2024.
SELECT P.BEAR_ID, BEAR_NAME, TOTAL_DISTANCE_TRAVELED 
FROM POLAR_BEARS P
LEFT JOIN (
SELECT BEAR_ID, SUM(DISTANCE_KM) AS TOTAL_DISTANCE_TRAVELED  
FROM TRACKING 
WHERE DATE BETWEEN '2024-12-01' AND '2024-12-31'
GROUP BY BEAR_ID) T
ON P.BEAR_ID = T.BEAR_ID
ORDER BY TOTAL_DISTANCE_TRAVELED DESC
LIMIT 3